- plugins/src/webrtcsink/imp.rs
And dot consumer pipelines on state changes.
> Add properties to set stun and turn servers

- plugins/src/webrtcsink/imp.rs
Allowing user to add a data channel for example
> sink: Add a `new-webrtcbin` signal

- Cargo.lock
- plugins/src/webrtcsink/imp.rs
- plugins/src/webrtcsink/mod.rs
Instead of hardcoding those.
Also update dependencies again.
> Add properties to set minimum and maximum bitrate values

- Cargo.lock
- README.md
- plugins/Cargo.toml
- plugins/src/webrtcsink/imp.rs
- plugins/src/webrtcsink/mod.rs
- signalling/simple-server.py
- www/index.html
- www/input.js
- www/keyboard.js
- www/webrtc.js
This allows interacting with the source element from within the browser very easily.
> Implement the GstNavigation interface using a dedicated DataChannel protocol

- README.md
> Update README.md with correct repo and branch

- Cargo.lock
- plugins/Cargo.toml
And update all other dependencies.
> Update to gstreamer-rs 0.18 instead of using it from git

- plugins/src/webrtcsink/imp.rs
> Add API to allow better tracking consumers

- plugins/src/webrtcsink/imp.rs
In order for applications to potentially create data channels at
the correct moment
> webrtcsink: emit consumer-added with webrtcbin in the Ready state

- plugins/examples/webrtcsink-stats-server.rs
- plugins/src/webrtcsink/imp.rs
+ refactor encoder-setup signal emission
+ document unused fields in navigation event handler
> webrtcsink: address Sebastian's latest comments

- plugins/src/webrtcsink/imp.rs
Low latency is very important for user interaction
> sink: Force data channel priority to high

- plugins/src/webrtcsink/imp.rs
Overlooked a superfluous unwrap() that caused the build to fail. Now it builds.
Also implemented all clippy suggestions.
> Remove erranous unwrap() on use_clock

- plugins/src/webrtcsink/imp.rs
Instead add it as a function and get the value from the encoder type.
This removes the necessity for any manual bookkeeping.
As per discussion in https://github.com/centricular/webrtcsink/issues/50#issuecomment-1111122804.
> Remove is_video field from Codec struct

- plugins/src/webrtcsink/imp.rs
From discussion at https://github.com/centricular/webrtcsink/issues/21#issuecomment-1032870763
> start_bitrate property, to allow specifying initial (video) bitrate

- Cargo.lock
- plugins/Cargo.toml
- plugins/src/signaller/imp.rs
- plugins/src/webrtcsink/imp.rs
- plugins/src/webrtcsink/utils.rs
- www/input.js
- www/keyboard.js
This adds support for the new touch screen events and modifier states introduced in gst 1.22. Tested in chromium.
> Add touch events and modifier states

- signalling/src/server/mod.rs
Some routers might otherwise time out websocket connections
Fixes #58
> signalling: send pings at 30-second intervals

- plugins/src/webrtcsink/imp.rs
- www/input.js
- www/webrtc.js
> Improve navigation support

- plugins/src/webrtcsink/imp.rs
> webrtcsink: don't use framerate halving as mitigation when 0/1

- plugins/src/webrtcsink/imp.rs
Computation of actual max bitrate was broken and in the end it is simpler
to keep the value set by the user and take into account the fec only
when required.
See https://github.com/centricular/webrtcsink/pull/85#issuecomment-1221073873
> webrtcsink: Fix the way we handle max-bitrate

- signalling/src/handlers/mod.rs
> Fix consumer disconnection

- plugins/src/webrtcsink/imp.rs
Fix case, when `bitrate` goes slightly higher than `max-bitrate` which leads to `fec-percentage` being out of range.
> gcc: Take fec and number of encoders into account

- plugins/src/webrtcsink/imp.rs
Following the PR #75 for adding support for memory:NVMM.
> Add support for memory:NVMM

- Cargo.lock
- plugins/Cargo.toml
gstreamer-rs rename ser_de feature to serde
> Change ser_de to serde

- plugins/src/webrtcsink/imp.rs
> Fix deadlocks
